version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: capistack
      POSTGRES_USER: capistack
      POSTGRES_PASSWORD: capistack
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U capistack"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for job queue and pub/sub
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # CapiStack Web Application
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql+psycopg://capistack:capistack@postgres:5432/capistack
      - REDIS_URL=redis://redis:6379/0
      - AUTH_MODE=none
      - SECRET_KEY=change_me_in_production
      - FERNET_KEY=base64url_32bytes_encryption_key_change_me
      - REPO_URL=https://github.com/owner/repo.git
      - GIT_PROVIDER=github
      - GIT_AUTH_TOKEN=your_token_here
      - PROJECT_NAME=My App
      - RUNNER_TYPE=local
      - WORK_DIR=/var/capistack/runs
    volumes:
      - ./runs:/var/capistack/runs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  # CapiStack Worker
  worker:
    build: .
    command: python jobs/worker.py
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql+psycopg://capistack:capistack@postgres:5432/capistack
      - REDIS_URL=redis://redis:6379/0
      - AUTH_MODE=none
      - SECRET_KEY=change_me_in_production
      - FERNET_KEY=base64url_32bytes_encryption_key_change_me
      - REPO_URL=https://github.com/owner/repo.git
      - GIT_PROVIDER=github
      - GIT_AUTH_TOKEN=your_token_here
      - PROJECT_NAME=My App
      - RUNNER_TYPE=local
      - WORK_DIR=/var/capistack/runs
    volumes:
      - ./runs:/var/capistack/runs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
